server:
  port: 8083

spring:
  application:
    name: order-service
  data:
    cassandra:
      keyspace-name: order_service
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 1
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        isolation.level: read_committed


jwt:
  secret: 7f3a8d2b9e4c1f6a5d8c3b7e9f2a4d6c8e1b3f5a7d9c2e4b6f8a1d3c5e7b9f2a
  expiration: 86400000
  header: Authorization
  prefix: Bearer

logging:
  level:
    org.springframework.data.cassandra: DEBUG